apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      upstream echo-server {
        server echo-server:8081; # Serviço do seu echo-server
      }

      server {
        listen 80;

        location / {
          proxy_pass http://echo-server; # Direciona para o serviço do backend
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
